#!/bin/bash

TARGET_DIR='/Volumes/Work/projects/code/haskell/toy/slate/static/'

cp scrib-save.js \
   scrib-view.js \
   ports.js \
   ui.js \
   version \
   $TARGET_DIR

cp -r resources/favicon/* $TARGET_DIR
cp -r resources/html/* $TARGET_DIR
cp -r resources/fonts $TARGET_DIR
cp -r resources/css $TARGET_DIR

echo "copied resources"
