#!/bin/bash

echo "Compiling View"
makeView
echo "Compiling Save"
makeSave
echo "Compiling Config"
makeConfig
echo "Compiling Page"
makePage
echo "Copying files"

copy-static '/Volumes/Work/projects/code/haskell/toy/slate/static/'