name: Scrib Build
on:
  push:
    branch:
      - main

jobs:
  build:
    name: Make Scrib
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install

      - name: Install Elm
        shell: bash
        env:
          ELM_VERSION: '0.19.1'
        run: |
          mkdir elm-compiler
          cd elm-compiler
          curl -L -o elm.gz "https://github.com/elm/compiler/releases/download/$ELM_VERSION/binary-for-linux-64-bit.gz"
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
          elm --version

      - name: Make Sources
        shell: bash
        run: |
          elm make src/Save.elm --optimize --output=scrib-save.js
          elm make src/View.elm --optimize --output=scrib-view.js
          ls -l ~

      - name: Install Elm Test
        shell: bash
        run: |
          npm install -g --unsafe-perm elm-test
          elm-test --version

      - name: Run Tests
        shell: bash
        run: |
          elm-test

      # - name: Copy Make Files
      #   shell: bash
      #   run: |
      #     mkdir dist
      #     cp config.html save.html view.html scrib-save.js scrib-view.js ports.js ui.js md.css scrib.png dist/
      #     ls -l dist/