name: Scrib Build
on:
  push:
    branch:
      - main

jobs:
  build:
    name: Make Scrib
    runs-on: ubuntu-latest
    env:
      ELM_VERSION: '0.19.1'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install

      - uses: actions/cache@v2.1.3
        name: Cache them builds
        with:
          path: ~/.elm
          key: Linux-elm-$ELM_VERSION

      - name: Install Elm
        shell: bash
        run: |
          mkdir elm-compiler
          cd elm-compiler
          curl -L -o elm.gz "https://github.com/elm/compiler/releases/download/$ELM_VERSION/binary-for-linux-64-bit.gz"
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
          elm --version

      - name: Make Sources
        shell: bash
        run: |
          ./build-optimized.sh Save scrib-save
          ./build-optimized.sh View scrib-view
          ./build-optimized.sh Config scrib-config

      - name: Install Elm Test
        shell: bash
        run: |
          npm install -g --unsafe-perm elm-test
          elm-test --version

      - name: Run Tests
        shell: bash
        run: |
          elm-test
