name: Scrib Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Make Scrib
    runs-on: ubuntu-latest
    env:
      ELM_VERSION: '0.19.1'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install

      - uses: actions/cache@v2.1.3
        name: Cache them builds
        with:
          path: ~/.elm
          key: Linux-elm-$ELM_VERSION

      - name: Install Elm
        shell: bash
        run: |
          mkdir elm-compiler
          cd elm-compiler
          curl -L -o elm.gz "https://github.com/elm/compiler/releases/download/$ELM_VERSION/binary-for-linux-64-bit.gz"
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
          elm --version

      - name: Make Sources
        shell: bash
        run: |
          ./build-optimized.sh Save scrib-save
          ./build-optimized.sh View scrib-view
          ./build-optimized.sh Config scrib-config

      - name: Install Minify
        shell: bash
        run: |
          npm install minify@v6.0.1 -g

      - name: Install Openssl
        shell: bash
        run: |
          sudo apt-get install openssl -y


      - name: Run Optimization
        shell: bash
        run: |
          mkdir staging dist
          ./optimized-copy-static.sh staging dist


      # - name: Copy Make Files
      #   shell: bash
      #   run: |
      #     mkdir dist
      #     ./copy-static dist

      - name: Zip Dist Files
        id: create-artifact
        shell: bash
        run: |
          cd dist
          zip -r ../scrib.zip *
          unzip -lf ../scrib.zip
          echo "::set-output name=artifact-name::scrib.zip"

      - uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: "${{ steps.create-artifact.outputs.artifact-name }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}